all : flash

TARGET:=debugprintfdemo
TARGET_MCU:=CH570
TARGET_MCU_PACKAGE:=CH570D

include ../../ch32fun/ch32fun.mk
# CFLAGS+= -Wno-volatile-register-var -ffixed-t6


flash : cv_flash
clean : cv_clean
